package words_str is 

   SEPARATOR : CHARACTER := ',' ;

   science : string := 
   "physics,chemistry,math,biology,astronomy," &
   "physiology,neurology," &
   "algebra,calculus,vectors," &
   "knuth,dijkstra,ullman,ritchie,kernighan,turing," &
   	"anatomy," &
	"heart," &
	"brain," &
	"kidney," &
	"liver," &
	"nerve," &
	"spine," &
	"cortex," &
	"neuron," &
	"skeleton," &
	"lung," &
	"lymph," &
	"axon," &
	"myelin," &
	"sheath," &
	"nucleus," &
	"dendrite," &
	"visceral," &
	"ganglion," &
	"synapse," &
	"vesicle," &
	"qualia," &
	"paradox," &
	"sapience," &
	"plasma," &
	"auricle," &
	"septum," &
	"artery," &
	"vein," &
	"platelet," &
	"mitral," &
	"aortic," &
	"carotid," &
	"coronary," &
	"atrium," &
	"renal," &
	"kidney," &
	"tissue," &
	"fetal," &
	"genesis," &
	"placenta," &
	"truncus," &
	"thoracic," &
	"thrombus," &
	"embolus," &
	"stent," &
	"stenosis," &
	"cephalic," &
	"cerebral," &
	"saliva," &
	"gastric," &
	"duodinum," &
	"pancreas," &
	"chyme," &
	"bile," &
	"gland," &
	"mucous," &
	"protein," &
	"vitamin," &
	"enzyme," &
	"thyroid," &
	"receptor," &
	"larynx," &
	"pharynx," &
	"pylorus," &
	"peptide," &
	"spleen," &
	"bone," &
	"marrow," &
	"hepatic," &
	"celiac," &
	"plexus," &
	"peptic," &
	"enteric," &
	"islet," &
	"stellate," &
	"parotid," &
	"glucose," &
	"dextrose," &
	"exocrine," &
	"retina," &
	"optic," &
	"chiasma," &
	"cornea," &
	"iris," &
	"cataract," &
	"blind," &
	"eye," &
	"wavelet," &
	"phase," &
	"spectrum," &
	"sinusoid," &
	"signal," &
	"amplify," &
	"aural," &
	"heat," &
	"thermal," &
	"fluid," &
	"flow," &
	"flux," &
	"laser," &
	"radar," &
	"lidar," &
	"canopy," &
	"microbe," &
	"mitosis," &
	"anole," &
	"moray," &
	"eel," &
	"anode," &
	"cathode," &
	"alpha," &
	"beta," &
	"gamma," &
	"bacteria," &
	"virus," &
	"hormone," &
	"dna," &
	"rna," &
	"mrna," &
	"atp," &
	"dawkins," &
	"sacks," &
	"knuth," &
	"aho," &
	"ullman," &
	"hopcroft," &
	"rivest," &
	"schneir," &
	"manber," &
	"occam," &
	"sisyphus," &
	"planet," &
	"galaxy," &
	"star," &
	"ada," &
	"python," &
	"perl," &
	"go," &
     "modula," &
     "cobol," &
     "rust," &
     "scala," &
     "flutter," &
     "oberon," &
	"ivy," &
	"oak," &
	"foxglove," &
	"azalea," &
	 "convection,radiation,pressure,saline,infect,umbilical,fetus,amneotic,placenta," &
	 "ovine,bovine,porcine," &
	 "embryo,spasm,aspirate,pulsatile,arterial,venous," &
	 "newton,einstein,galileo,gauss,fourier,harvey,maxwell,faraday,boole,higgs,chandra,bose,fermat,volta," &
   "" ;

   mythology : string :=
   "rama,krishna,sita,lakshmi,hanuman," &
   "zeus,hercules,atlas," &
   "" ;

   literature : string :=
   "dickens,dumas,stevens,steinbeck,joyce," &
   "tagore," &
   "" ;

   words : string := 
     "perfect," &
     "contronym,antonym,antagonym,enantiodrome,antilogy,antonius,antonomasia," &
     "synonym,synoecious,synoekete,synoicous,synonychia," &
     "arete," &
     "saudade,skerrick,flump,fustian,minatory,vamoose," &
     "busybody,gnashnab,snoutband,stampcrab,zooterkins,zounds,fopdoodle,foozle,klutz,mafflard,shot-clog,"&
     "rakefire," &
     "hubris,ossify,nimrod,kvell,tousle,liminal,abjure," &
	 "pangram,kennings,antigram,ambigram,acrostics," & 
	 "oaf,gull,clod,stooge,boob,dolt,chump,patsy,dupe," &
	 -- nym words
	 "acronym,allonym,ananym,andronym,antonym,aptonym,autonym,backronym,basionym,caconym," &
	 "capitonym,charactonym,contranym,cryptonym,demonym,endonym,eponym,ethnonym,exonym," &
	 "gynonym,heteronym,homonym,hydronym,hyponym,inaptonym,linguonym,matronym,meronym,metonym," &
	 "mononym,numeronym,odonym,oronym,paranym,pronym,patronym,plesionym,pseudonym,retronym," &
	 "synonym,tautonym,theonym,toponym,trionym," &
     "" ; 

end words_str ;
