package words_str is 
   words : string := 
	"anatomy," &
	"heart," &
	"brain," &
	"kidney," &
	"liver," &
	"nerve," &
	"spine," &
	"cortex," &
	"neuron," &
	"skeleton," &
	"lung," &
	"lymph," &
	"axon," &
	"myelin," &
	"sheath," &
	"nucleus," &
	"dendrite," &
	"visceral," &
	"ganglion," &
	"synapse," &
	"vesicle," &
	"qualia," &
	"paradox," &
	"sapience," &
	"plasma," &
	"auricle," &
	"septum," &
	"artery," &
	"vein," &
	"platelet," &
	"mitral," &
	"aortic," &
	"carotid," &
	"coronary," &
	"atrium," &
	"renal," &
	"kidney," &
	"tissue," &
	"fetal," &
	"genesis," &
	"placenta," &
	"truncus," &
	"thoracic," &
	"thrombus," &
	"embolus," &
	"stent," &
	"stenosis," &
	"cephalic," &
	"cerebral," &
	"saliva," &
	"gastric," &
	"duodinum," &
	"pancreas," &
	"chyme," &
	"bile," &
	"gland," &
	"mucous," &
	"protein," &
	"vitamin," &
	"enzyme," &
	"thyroid," &
	"receptor," &
	"umami," &
	"larynx," &
	"pharynx," &
	"pylorus," &
	"peptide," &
	"spleen," &
	"bone," &
	"marrow," &
	"hepatic," &
	"celiac," &
	"plexus," &
	"peptic," &
	"enteric," &
	"islet," &
	"stellate," &
	"parotid," &
	"glucose," &
	"dextrose," &
	"exocrine," &
	"retina," &
	"optic," &
	"chiasma," &
	"cornea," &
	"iris," &
	"cataract," &
	"blind," &
	"eye," &
	"wavelet," &
	"phase," &
	"spectrum," &
	"sinusoid," &
	"signal," &
	"amplify," &
	"aural," &
	"heat," &
	"thermal," &
	"fluid," &
	"flow," &
	"flux," &
	"laser," &
	"radar," &
	"lidar," &
	"canopy," &
	"microbe," &
	"mitosis," &
	"anole," &
	"moray," &
	"eel," &
	"anode," &
	"cathode," &
	"alpha," &
	"beta," &
	"gamma," &
	"bacteria," &
	"virus," &
	"hormone," &
	"dna," &
	"rna," &
	"mrna," &
	"atp," &
	"krishnan," &
	"raman," &
	"gopalan," &
	"sita," &
	"durga," &
	"bagyam," &
	"lakshmi," &
	"shyama," &
	"sivan," &
	"andolika," &
	"bhairavi," &
	"todi," &
	"natai," &
	"gowla," &
	"kanada," &
	"arabi," &
	"varali," &
	"sri," &
	"hindolam," &
	"kurinji," &
	"revati," &
	"adi," &
	"rupakam," &
	"chapu," &
	"misram," &
	"tisram," &
	"ekam," &
	"kandam," &
	"kalyani," &
	"dickens," &
	"dumas," &
	"dawkins," &
	"sacks," &
	"knuth," &
	"aho," &
	"ullman," &
	"hopcroft," &
	"rivest," &
	"schneir," &
	"manber," &
	"occam," &
	"sisyphus," &
	"planet," &
	"galaxy," &
	"star," &
	"ada," &
	"python," &
	"perl," &
	"go," &
     "modula," &
     "cobol," &
     "rust," &
     "scala," &
     "flutter," &
     "oberon," &
	"ivy," &
	"oak," &
	"foxglove," &
	"azalea," &
	"nettle," &
     "oleander," &
     "hogweed," &
     "parsnip," &
     "jimsonweed," &
     "bonsai," &
     "prime," &
     "perfect," &
     
     "" ; 
end words_str ;
